### ISSUE TITLE
Alert to a discrepancy or difference in balance  

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#119]
Event will no longer show as "Billed, needs to be paid" if any amount of the balance is paid with a minimum of one payment per bill.

Not sure how often someone will under pay us but if we are going to have the functionality it needs to work. Or this should simply become a "paid" field not "paid this amount"

**Comment by jmerdich** [comment]
Per 2 treasurers, this behavior is desirable.
