### ISSUE TITLE
Calendar View of Events

### ISSUE THREAD

**Issue by dph119** [WPI-LNL/lnldb#136]
Similar to the old database, some way to view all events in a calendar format would be nice (though not imperative). Consider it a neat feature to implement down the road?

![screen shot 2014-01-22 at 6 43 37 pm](https://f.cloud.github.com/assets/5940007/1980296/1fd9341e-83bf-11e3-84ee-d24ef34281f5.png)

**Comment by jmerdich** [comment]
Done a while back.
