### ISSUE TITLE
Manually Print IDT

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#168]
This probably wont be done until #24 is worked on however I will log it for now.

It would be nice to have a "Print" button next to the update and delete button. This would allow an IDT (that is normally sent via email) to be printed manually without sending an email.

![image](https://f.cloud.github.com/assets/5770438/2032078/37bf5de2-890a-11e3-8d91-7cc2c248fb8a.png)

**Comment by jmerdich** [comment]
We now have a invoice pdf generator, but IDTs are out of scope for the moment. The hard part is the invoice anyways.
