### ISSUE TITLE
Associated Orgs Does Not Work

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#204]
....I think.

I am not exactly sure how it is supposed to work so. When i add an org as associated on the matching client record it shows it is now associated,

User does not appear to be able to submit a work order for associated clients or view previous work orders. If this is not already implemented she should talk about how we think this should work. There are a few ideas about cascading one way vs another so we should make sure we are on the same page.

**Comment by jmerdich** [comment]
See #232
