### ISSUE TITLE
When do New Users become "Contact Users"

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#228]
I noticed all new users come into the DB unassociated with any role as and there for are displayed as unassocated. At what point do they become a contact user? When they are a contact for their first event? 

Continuing down this path is there any practical difference between the two? It seems that unassocated and contact users appear in the same searches, so is this only an internal administrative filtering?

**Comment by jmerdich** [comment]
Will be re-addressed in DB3, as all users would have at least rudimentary access and be considered capable of booking events. Whether they booked an event recently may be a good idea for a filter/view/column, but a group for it is unnecessary. These points may, however, apply to organization owners.

**Comment by jmerdich** [comment]
Answer: never. Users are users. Since there is no easy way to maintain 'active' contacts in a group, any such thing should be done with a database query and not a group. As of now, everyone has adequate permissions on their own events anyways (see `events/perms.py`).
