### ISSUE TITLE
Associated Orgs

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#232]
This feature is interesting and left now start to jump down this rabit hole.

Case:
B is associated with A so ... A <-> B

Does this mean users from A can submit to B?  ... I would hope so
Does this mean users from B can submit to A? ... I would hope so

Now here is were things get interesting
B is associated with A so ... A <-> B
C is associated with A so ... A <-> C

So is B associated with C now? Based on the linking I see in the DB I am guessing no, is this right?

On a related note I doesn't seem that related orgs is working at all regardless of the above security question.

**Comment by jmerdich** [comment]
Marking associated orgs for the axe in the future. The MCF-T/ATC relation is the only one in the db, and all the functionality you really need is handled by normalized funds.

**Comment by mcf747** [comment]
100% agree. This was a stop gap because normalized funds did not exist.
Thank all that is holly now that you have done that.

**Comment by gmorell** [comment]
:+1:

**Comment by mcf747** [comment]
I just re-read this....MCF Tech was the only relationship? Soccom should
have also been there....weird. I used MCF Tech and ATC to test LOL

**Comment by jmerdich** [comment]
Obsolete with multiple funds per org.

**Comment by mcf747** [comment]
Thank god
