### ISSUE TITLE
New Meeting Notice List has odd thing sit again

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#254]
As of today (4/2/2014) the Alpah Phi formal and Thor 2 are showing in the New Meeting notice box even though they already happened.

Can we review the logic of this box....

![image](https://cloud.githubusercontent.com/assets/5770438/2599365/a0e2a70a-badf-11e3-870c-2888f60b44c4.png)

**Comment by jmerdich** [comment]
Closed as dupe of #253
