### ISSUE TITLE
Discuss Deprecated Feilds

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#260]
We should discuss this before anything is done but there are a bunch of fields in django that are no longer used due to re-factoring over time. The fields should be hidden from django and we should document there deprecation.

From the events side http://lnl.wpi.edu/admin/events/event/15063/

I think the following fields are no longer used/implemented elsewhere:
1. Contact_name ... now (pulled from Contact record) right? relates #233 
2. Contact email ... now (pulled from Contact record) right?
3. Contact addr ... now (pulled from Contact record) right?
4. Contact phone ... now (pulled from Contact record) right?
5. Datetime setup start ... now in CC record right?
6. Setup location .. now in CC record right?
7. Payment amount .. now in billing?
8. Crew chief .. separate table now right?
9. Crew... separate table now right?

We should also decide if we want to re-factor the database or just hide the fields from django.

**Comment by jmerdich** [comment]
Removed certain redundant info about a month ago. All of this stuff is either verified migrated or too old to be of any use.
