### ISSUE TITLE
Local user Discussion

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#262]
We allow a user to be created form the front end under Misc but we never let them set a password so there is no way to make a local user form the front end. A WPI user can be made b/c no password is set.

I also realized once you set a password there is no way to set it to "Null" and allow the user to auth via CCC. I realize there is no normal use case  for this but it a CCC user ever had a password set accidentally (especially once we expose it in the front end) there is no way (currently) to un-set the password.

**Comment by jmerdich** [comment]
Frontend user creation is currently supported, no more discussion necessary. Some aspects (ie. password reset + global logout) don't work and are a different issue.
