### ISSUE TITLE
/my tweeks

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#265]
reorder cced events to make most recent show on top, this should only apply to cced events, not the other two lists pn the page at the link bellow
http://lnl.wpi.edu/my/events/

my previous workorders at this page http://lnl.wpi.edu/my/workorders/ should display events for orgs that you are the owner aka "in charge of" OR assocated with. right now it only shows events for events you are assocated with regardless of owner status. since we made owner and assocated independant this is an issue.

under my previous workorder clients should be able to print there old workorders (display pdf) and also view there bills once we get all that working.....

**Comment by jmerdich** [comment]
My is totally new, anyhow. Links to all the proper event pages.
