### ISSUE TITLE
Events Pending Review Logic

### ISSUE THREAD

**Issue by mcf747** [WPI-LNL/lnldb#272]
AS of 4/15/2014 at 1:11am the Grad Students Got Talent has not happened yet so why is it displaying in the Events Pending Review?

![image](https://cloud.githubusercontent.com/assets/5770438/2703819/84d111ba-c45c-11e3-9914-4787e1041bfb.png)

**Comment by jmerdich** [comment]
Irrelevant, as all of the list views got refactored last week.
