### ISSUE TITLE
Fix "User in charge" box on New Client page

### ISSUE THREAD

**Issue by rrlapointe** [WPI-LNL/lnldb#420]
When you select a person in the "User in charge" box on the New Client page, it empties the text box (correct behavior) and then doesn't let you press Save Changes because it is empty (incorrect behavior because a person is selected and their name is displayed below the box).

**Comment by rrlapointe** [comment]
Also affects the Edit Client page

**Comment by tnurse18** [comment]
Is this still an issue? I can't seem to recreate it.
