### ISSUE TITLE
Test coverage = sad

### ISSUE THREAD

**Issue by tnurse18** [WPI-LNL/lnldb#467]
Even an entire summer of writing tests for the untested code in this project hasn't quite been enough. Here's a list of modules where testing is still insufficient:

- [x] Data
- [x] Events
- [x] Meetings
- [x] Members

By the end of the calendar year, the overall coverage should really be in the 90% range. We will need to drop support for python 2 before 2021 or we could run into more problems.

**Comment by rrlapointe** [comment]
I assume you meant to say "drop support for python 2"

**Comment by tnurse18** [comment]
Yes, thank you
