### ISSUE TITLE
Outlook invites

### ISSUE THREAD

**Issue by tnurse18** [WPI-LNL/lnldb#561]
Add an option to _automatically_ send Outlook invites for meetings and/or events. We can develop a manual mechanism for this as well, but that should probably wait until we have a system in place for user-specific preferences. Most of the functionality is already there, it just needs to be implemented in the UI.

_Note: There would be a difference between the ics files that we currently attach to some of our emails and these calendar invites. Contact the webmaster for more details._

**Comment by yellowjaguar5** [comment]
At some point, we can revisit deep-linking into Outlook on desktop/mobile (since the current URL scheme often requires users to authenticate). E.g. `ms-outlook://events/new?title=A%20Meeting&location=loc&start=2020-12-31T19:30:00Z&end=2020-12-31T22:30:00Z&body=The%20description`

**Comment by yellowjaguar5** [comment]
I'm not sure I have the full understanding to work on this now. If anyone's interested, feel free to work on it.
