### ISSUE TITLE
Meeting doubling

### ISSUE THREAD

**Issue by otherNatalie** [WPI-LNL/lnldb#588]
Sometimes the meetings double create. I know the meeting email issue was because I hit the button 3 times, but I'm not sure if the meeting create was the same

**Comment by tnurse18** [comment]
I have been unsuccessful in replicating this issue. Are you able to provide more details as to exactly when this has happened? If not, has anyone else encountered this problem?

**Comment by otherNatalie** [comment]
Yeah to be honest I have no idea what caused it, I couldn’t recreate it when I tried to submit the ticket. My guess is double clicking buttons meant it did the action twice? I know that’s what caused the email tripling.


Thanks,

Natalie

--

Natalie McClain

She/Her/Hers
Computer Science, Class of 2023
Student Assistant, Computer Science Department
Technical Director, VOX Musical Theatre
Secretary, WPI Lens and Lights ***@***.******@***.***>)

From: Tom ***@***.***>
Sent: Thursday, December 9, 2021 9:40 PM
To: ***@***.***>
Cc: McClain, Natalie ***@***.***>; ***@***.***>
Subject: [EXT] Re: [WPI-LNL/lnldb] Meeting doubling (Issue #588)


I have been unsuccessful in replicating this issue. Are you able to provide more details as to exactly when this has happened? If not, has anyone else encountered this problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWPI-LNL%2Flnldb%2Fissues%2F588%23issuecomment-990553837&data=04%7C01%7Cnmcclain%40wpi.edu%7C30619542bbec42c43aca08d9bb865d6c%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637747008063468082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cf2bA5CKZNLJ%2FXu0CdzJLruizqnbSCq%2BRnIa2UOt8dA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAN7LBYOSK2FNZOOHGJ4GGO3UQFSADANCNFSM5JUWFCEQ&data=04%7C01%7Cnmcclain%40wpi.edu%7C30619542bbec42c43aca08d9bb865d6c%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637747008063468082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wZL5k5iKu1tH6lhvy1cC%2BkptzX%2B84TOAQZM%2FXgi9z%2Fc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnmcclain%40wpi.edu%7C30619542bbec42c43aca08d9bb865d6c%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637747008063468082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dm7Tu36gia9FQgdSelIqA7ME6THUJH4uur6AiQGPIDg%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnmcclain%40wpi.edu%7C30619542bbec42c43aca08d9bb865d6c%7C589c76f5ca1541f9884b55ec15a0672a%7C0%7C0%7C637747008063468082%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2u18hSVaGVBBDvwF%2FscFcUg6%2BJNp%2FxwA1YsOGI6z0dE%3D&reserved=0>.
