### ISSUE TITLE
Workorder Wizard sign in redirects to `/db`

### ISSUE THREAD

**Issue by benjamin-antupit** [WPI-LNL/lnldb#735]
When not logged in, user nagivates to `/workorder`, gets redirected to `/signin`, signs in with Microsoft, and gets redirected to `/db`, but should be redirected to `/workorder`. This could be confusing for clients who don't usually interface with the DB and only look at the Workorder Wizard.

**Comment by alextannenbaum** [comment]
The workorder wizard is gone
