### ISSUE TITLE
Switch Markdown Editor

### ISSUE THREAD

**Issue by i-am-gizm0** [WPI-LNL/lnldb#739]
[Monaco editor](https://github.com/microsoft/monaco-editor) is the actual text editor part of VS Code. Using it allows syntax highlighting, keyboard shortcuts, and (really the thing i actually want here) uses a monospace font.

**Comment by benjamin-antupit** [comment]
I'm going to try [`django-simplemde`](https://github.com/onepill/django-simplemde) and see how it goes. Open to feedback.

**Comment by benjamin-antupit** [comment]
We switched to a new markdown editor! @i-am-gizm0 Please try it out and let me know what you think.
