### ISSUE TITLE
SSO login loses "next" parameter

### ISSUE THREAD

**Issue by i-am-gizm0** [WPI-LNL/lnldb#812]
Clicking a link to the DB when not authenticated redirects you to `https://lnl.wpi.edu/login/?next=<path>`, as it should.
However, after authenticating with Microsoft, you are sent just to `https://lnl.wpi.edu/db/`.

Somewhere in the SAML chain, the `next` parameter is getting dropped.

![browser request log](https://github.com/WPI-LNL/lnldb/assets/20424374/e8fe56be-4973-4a76-a741-b1583881b6d3)

I can also provide a browser request trace.

**Comment by alextannenbaum** [comment]
Fixed
