### ISSUE TITLE
add chatgpt intergration to the work order wizard

### ISSUE THREAD

**Issue by salochinYom** [WPI-LNL/lnldb#876]
add a chatbot to the work order wizard to reduce VP workload.

As the client I don't know what exactly what information LNL needs from me and im afraid of asking questions. I would like the chat bot assist me in answering the required questions needed to quote the event. I would also like the chatbot to remeber me in case i need to exit the site while getting a quote. the system should be able to give estimates that are subject to approval by a human.

As an exec board member/authorized member of the club i would like to be able to view an AI generated summary from the chatbot including the following information

- Date of the event
- corosponding 25 live booking
- services requested
- potential issues with the services being requested
- contact information of the client in the form of an email and/or the associated external slack channel within the 

I would also like to be able to view the Chat logs with the client in case more information that does not warrent an email to the client is required.

the system should not be able to send binding quotes to clients.

**Comment by i-am-gizm0** [comment]
![91xuna.jpg](https://github.com/user-attachments/assets/a882d218-455c-4b70-aeec-86d079f4e47d)

**Comment by alextannenbaum** [comment]
fired
